version: '3.8'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/proxy.conf.template:/etc/nginx/proxy.conf.template
      - ./docker/nginx/docker-entrypoint.sh:/docker-entrypoint-mount.sh
      - ./docker/nginx/certs:/etc/ssl
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${SSL_PORT:-443}:443"
    environment:
      - NGINX_WORKER_PROCESSES=${NGINX_WORKER_PROCESSES:-1}
      - NGINX_KEEPALIVE_TIMEOUT=${NGINX_KEEPALIVE_TIMEOUT:-65}
      - NGINX_CLIENT_MAX_BODY_SIZE=${NGINX_CLIENT_MAX_BODY_SIZE:-75M}
      - NGINX_PROXY_READ_TIMEOUT=${NGINX_PROXY_READ_TIMEOUT:-60s}
      - NGINX_PROXY_SEND_TIMEOUT=${NGINX_PROXY_SEND_TIMEOUT:-60s}
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME:-localhost}
      - NGINX_PORT=${NGINX_PORT:-80}
      - NGINX_HTTPS_ENABLED=${NGINX_HTTPS_ENABLED:-false}
      - NGINX_SSL_CERT_FILENAME=${NGINX_SSL_CERT_FILENAME:-cert.pem}
      - NGINX_SSL_CERT_KEY_FILENAME=${NGINX_SSL_CERT_KEY_FILENAME:-key.pem}
      - NGINX_ENABLE_CERTBOT_CHALLENGE=${NGINX_ENABLE_CERTBOT_CHALLENGE:-false}
    entrypoint: [ 'sh', '-c', "cp /docker-entrypoint-mount.sh /docker-entrypoint.sh && sed -i 's/\r$$//' /docker-entrypoint.sh && chmod 777 /docker-entrypoint.sh && /bin/sh docker-entrypoint.sh" ]
    networks:
      - app-network

  web:
    image: dify-chat-portal:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    networks:
      - app-network

  api:
    image: dify-chat-portal-api:latest
    expose:
      - "8000"
    volumes:
      - ./api/data:/app/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 